source 'https://rubygems.org'

gem 'rake', '~> 13.0'
gem 'rake_dependencies', '~> 2.5'
gem 'rake_terraform', '~> 1.9'
gem 'rake_circle_ci', '~> 0.7'
gem 'rake_github', '~> 0.5'
gem 'rake_ssh', '~> 0.4'
gem 'confidante', '~> 0.21'
gem 'rspec', '~> 3.9'
gem 'awspec', '~> 1.22'
gem 'git', '~> 1.7'
gem 'semantic', '~> 1.6'
