---
configuration_directory: "%{cwd}/examples/full"
state_file: "%{cwd}/state/full.tfstate"
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  lambda_function_name: "%{hiera('lambda_function_name')}"
  lambda_description: "%{hiera('lambda_description')}"

  lambda_zip_path: "%{hiera('lambda_zip_path')}"
  lambda_handler: "%{hiera('lambda_handler')}"
